export const coursesData = [
  {
    id: 1,
    url: "./images/1.webp",
    title: "iOS Development",
    description: "რეგისტრაცია დასრულებულია",
    button: "კურსის დეტალები",
  },
  {
    id: 2,
    url: "./images/2.webp",
    title: "React",
    description: "რეგისტრაცია დასრულებულია",
    button: "კურსის დეტალები",
  },
  {
    id: 3,
    url: "./images/3.webp",
    title: "Intro to Python",
    description: "რეგისტრაცია დასრულებულია",
    button: "კურსის დეტალები",
  },
  {
    id: 4,
    url: "./images/4.webp",
    title: "Advanced Python",
    description: "რეგისტრაცია დასრულებულია",
    button: "კურსის დეტალები",
  },
  {
    id: 5,
    url: "./images/5.webp",
    title: "Advanced Cybersecurity Course",
    description: "რეგისტრაცია დასრულებულია",
    button: "კურსის დეტალები",
  },
  {
    id: 6,
    url: "./images/6.webp",
    title: "ToT - Training of Trainers",
    description: "რეგისტრაცია დასრულებულია",
    button: "კურსის დეტალები",
  },
  {
    id: 7,
    url: "./images/7.webp",
    title: "Blockchain",
    description: "რეგისტრაცია დასრულებულია",
    button: "კურსის დეტალები",
  },
  {
    id: 8,
    url: "./images/8.webp",
    title: "DevOps",
    description: "რეგისტრაცია დასრულებულია",
    button: "კურსის დეტალები",
  },
  {
    id: 9,
    url: "./images/9.webp",
    title: "Information Security Governance",
    description: "რეგისტრაცია დასრულებულია",
    button: "კურსის დეტალები",
  },
];
